### ISSUE TITLE
[24-25회차] 제너레이터와 async await, 모듈, 에러

### ISSUE THREAD

**Issue by taboowiths** [FrontCS-Study/CS-Study#10]
- @yeonsu-k  async function과 Promise의 차이는?
- @taboowiths JavaScript에서 모듈을 사용할 때의 장점 2가지를 말해보세요.

**Comment by unhhyyeexx** [comment]
1. promise를 더욱 쉽게 사용할 수 있도록 만든 문법이 async/await 이다. 
   에러를 처리할 때 Promise는 `.catch()`문을 통해 에러핸들링을 하고, async/await에서는 `try-catch`문을 활용한다.
   Promise에서 `.then()`지옥의 가능성이 있기 때문에, 코드가 길어질수록 async/await을 활용한 코드가 가독성이 좋다. async/await은 비동기처리를 해주지만 동기 코드처럼 익히기 해주어 코드 흐름을 이해하기 쉽다.
2. 모듈을 사용하면 재사용이 가능해 개발과 유지보수가 용이해진다. 또한 하나의 파일에 하나의 클래스만 포함시키고 단 하나의 기능만 담당하도록 하는 등, 기능의 분리가 가능해 인터페이스가 단순해진다.

**Comment by yeonsu-k** [comment]
1. Promise는 then,catch,finally라는 후속 처리 메서드가 존재합니다. 하지만 프로미스도 then()을 연속으로 작성하면 콜백 지옥이 생길 수 있습니다. async 는 이런 Promise의 가 아닌 값이더라도 Promise로 값을 감싸 이행된 Promise로 반환됩니다. 더불어 await와 함께 사용할 경우, 비동기를 동기 처럼 직관적이고 쉽게 처리할 수 있고, 동기와 비동기 구분 없이 try/catch로 예외처리 할 수 있습니다.

2.  똑같은 코드를 반복하지 않고 필요할 때만 사용할 수 있는 재사용성과 모듈화된 만큼 의존성을 줄일 수 있기 때문에 코드 개선과 수정할 때 비용을 절감할 수 있는 유지보수성에 좋습니다.

**Comment by taboowiths** [comment]
- 자바스크립트의 비동기 처리 시 사용하는 Promise 객체는 내부적으로 .then(), .catch() 등의 키워드를 이용하여 비동기 처리의 결과를 순차적으로 처리할 수 있다. async function은, `async` 키워드가 붙은 함수로, 항상 Promise 객체를 반환한다. async 함수가 실행되고 내부에서 `await` 키워드를 만나게 되면, async 함수가 반환하는 Promise 객체를 기다린 후, Promise의 상태에 따라 그 다음 코드로 넘어간다. 이 때 Promise객체의 .then() 핸들러를 따로 사용하지 않아도 코드를 순차적으로 처리할 수 있다.
- 모듈을 분리하여 얻을 수 있는 장점은 1) 모듈화로 인해 코드의 의존성이 줄어 유지보수성이 좋아진다는 것과, 2) 똑같은 코드를 반복하여 사용하지 않고 분리하여 필요할 때 불러와 사용할 수 있다는 점이 있다.
