### ISSUE TITLE
[26회차] React, virtual DOM

### ISSUE THREAD

**Issue by yeonsu-k** [FrontCS-Study/CS-Study#11]
1. @yeonsu-k virtual DOM이 좋은 이유
2. @unhhyyeexx React의 장점
3. @taboowiths Angular와 Vue.js와 비교했을 때, React의 특징 한 가지

**Comment by taboowiths** [comment]
1. VirtualDOM 은 화면에 DOM과 동일한 가상의 DOM으로, 리페인팅과 리플로우가 수행되면 해당 변경사항들을 Virtual DOM에 기록했다가 원본 DOM과 비교하여 변경사항을 반영할 수 있도록 한다. 연산을 최소화하기 때문에, 하나하나의 변경사항을 원본 DOM에 반영하는 것보다 성능면에서 이점을 가진다.

2. React의 장점은 VirtualDOM으로 성능을 최소화한 것, 라이브러리이기 때문에 다른 프레임워크나 라이프러리와 혼용이 가능하여 유연하게 적용할 수 있는 것, 자바스크립트 문법을 사용하기 때문에 비교적 쉽게 사용이 가능하다는 점이 있다.

3. Augluar와 Vue.js는 프레임워크로, 해당 프레임워크가 제공하는 구조와 규칙 내에서 개발해야 한다. React는 라이브러리로, 개발자가 호출을 통해 사용할 수 있어 직접 코드의 흐름과 제어를 관리한다.

**Comment by unhhyyeexx** [comment]
1. 가상돔은 자바스크립트 객체의 형태로 표현되며 메모리 상에서 동작하기 때문에 빠르면서, 실제 렌더링을 하는 dom에 비해 연산 시간이 짧아질 수 있다.
2. 1. 리액트는 활발하고 다양한 커뮤니티와 생태계를 가지고 있어 문제 해결을 위한 자료와 지원을 쉽게 얻을 수 있다.
   2. 컴포넌트를 독립적으로 관리하고 이를 이용해 화면 구성을 할 수 있는데, 손쉽게 컴포넌트를 재사용 할 수 있리에 추가 개발 지원 및 최적화가 쉽다.
   3. 가상돔을 사용해 대규모 SPA와 다이나믹 UI의 웹페이지에서도 충분히 빠른 속도를 유지할 수 있다.
3. 앵귤러와 뷰는 자신만의 문법이 있지만, 리액트는 자바스크립트 기반의 문법을 사용하기 때문에 자바스크립트에 익숙하다면 보다 쉽게 사용이 가능하다. 또한 뷰와 앵귤러는 프레임원크, 리액트는 라이브러리로, 제어의 흐름이 개발자에게 있다.

**Comment by yeonsu-k** [comment]
1. 
> 효율성에 좋습니다. 실제 DOM은 10번의 변화가 생기면 렌더링 역시 10번이 이루어지기 때문에  프로세스적으로 비효율적입니다. 가상돔을 사용할 경우, DOM의 복사본을 메모리에 저장하고 변경 상태를 비교하여 바뀐 일부분만 실제 DOM에 적용하기 때문에     한번의 렌더링 과정만 거칠 수 있습니다. 이러한 과정으로 속도, 메모리측면에서도 실제 DOM보다 가상돔이 효율적이므로 가상돔을 사용합니다.
2. 
> Angular, Vue와 달리 자바스크립트 문법을 그대로 사용합니다.
리액트는 라이브러리로 개발 확장성에 좋습니다.
리액트네이티브나 VR 처럼 웹 이외에 기술 확장성에도 좋습니다.
가상돔을 사용해 빠른 렌더링이 가능합니다.
3.
> Angular, Vue와 달리 자바스크립트 문법을 그대로 사용한다. 또한 Angular,Vue는 프레임워크로 개발자는 정해진 틀 내에 코드를 작성해야하는 반면에 React는 라이브러리로 개발자가 필요한 기능을 호출해서 직접 관리할 수 있다.
