### ISSUE TITLE
[27회차] 컴포넌트 / props, state

### ISSUE THREAD

**Issue by unhhyyeexx** [FrontCS-Study/CS-Study#12]
1. @unhhyyeexx 리액트 컴포넌트란 무엇인가요?
2. @taboowiths 함수 컴포넌트와 클래스 컴포넌트의 차이는 무엇인가요?
3. @yeonsu-k 리액트에서 클래스 컴포넌트보다 함수 컴포넌트를 사용하는 이유가 뭘까요?

**Comment by taboowiths** [comment]
1. 리액트에서 컴포넌트란 UI를 구성하는 기본 단위이다. 각각의 컴포넌트가 각 기능을 가지고 동작한다.

2. 함수 컴포넌트와 클래스 컴포넌트의 차이는 
    1) 함수 컴포넌트는 JavaScript의 함수를 기반으로  구성된 컴포넌트, 클래스 컴포넌트는 JavaScript의 클래스를 기반으로 하는 컴포넌트이다. 
    2) 함수 컴포넌트는 부모 컴포넌트로부터 props를 받아 사용할 수 있고, state와 같은 동적인 데이터를 사용하지 못했으나, React 16부터 제공하는 hook(useState)를 이용할 수 있다. 클래스 컴포넌트는 props, state, refs나 lifecycle 메소드 등을 사용할 수 있다. 

3. React에서 제공하는 다양한 hook 을 사용해 자원을 효율적으로 관리하기 편해졌다. 또 JavaScript의 문법 (화살표 함수, 함수 선언 등)을 그대로 사용하기 때문에, 코드가 직관적이다. 그리고 클래스 컴포넌트에 비해 비교적 메모리 자원을 적게 사용한다. 마지막으로 React가 함수 컴포넌트 사용을 더 권장한다.

**Comment by yeonsu-k** [comment]
1. 
> 컴포넌트는 리액트 앱을 이루는 최소한의 단위입니다. 리액트로 만든 앱은 여러개의 컴포넌트로 구성되어 있습니다. 컴포넌트는 함수형과 클래스형으로 두 종류를 가지고 있습니다.
2. 
> 클래스형 컴포넌트는 코드 안에 라이프사이클 기능과 state 기능이 구현이 가능하고, 함수형 컴포넌트는 hook을 사용하여 라이프사이클 기능과 state기능을 구현할 수 있습니다. 또한 클래스는 render() 메서드가 필수적으로 사용해야 합니다.
3.
> 함수형은 render()함수가 필요 없어서 클래스형 컴포넌트 보다 마운트 속도가 더 빠르고, 가독성이 좋을 뿐만아니라, 메모리 자원, 빌드 후 파일 크기도 더 작습니다.  
또한, React v16 이후부터 Hooks를 통한 state 및 LifeCycle 관리가 가능해지면서 리액트에서 공식적으로 함수형 컴포넌트 사용을 권장하고 있습니다.

**Comment by unhhyyeexx** [comment]
1. 리액트에서 화면 UI를 구분할 때 쓰는 단위로, 앱을 이루는 가장 작은 단위라고 할 수 있다. 컴포넌트는 새로운 컴포넌트를 생성할 수도 있고, MVC의 뷰를 독립적으로 구성해 재사용할 수 있다. 리액트의 중요한 핵심인 '컴포넌트'에는 함수 컴포넌트, 클래스 컴포넌트 두 가지가 있다.
2. 클래스 컴포넌트는 자바스크립트의 클래스를 기반으로 하고 render()함수에서 jsx 코드를 반환한다.
   함수컴포넌트는 자바스크립트의 함수를 기반으로 하는 컴포넌트 이고, function으로 컴포넌트를 정의하고 return문에 jsx코드를 반환한다.
3. 1. 과거에는 함수형 컴포넌트가 state, 라이프사이클을 지원하지 않았지만, 현재는 hook을 통한 state관리 및 라이프사이클 관리가 가능해졌다.
   2. 함수 선언, 화살표 함수를 그대로 사용하기 때문에 개발자에게 직관적이다.
   3. 클래스형 컴포넌트에 비해 비교적 메모리 자원을 적게 사용한다.
