### ISSUE TITLE
[28회차] Flux, Redux, 불변성

### ISSUE THREAD

**Issue by unhhyyeexx** [FrontCS-Study/CS-Study#13]
1. @unhhyyeexx React 자체적으로 state관리가 가능한테 Redux를 사용하는 이유가 무엇일까요?
2. @yeonsu-k state를 직접 변경하지 않고 setState를 사용하는 이유에 대해서 설명해주세요.

**Comment by unhhyyeexx** [comment]
1. 리액트 컴포넌트 별로 state를 외부 라이브러리 없이 관리할 수 있다. 하지만 컴포넌트의 양이 많아지고, state를 공유해야 할 경우가 늘어나면 공통 컴포넌트들을 부모 컴포넌트에서 관리하며 자식 컴포넌트에 props로 주입해주는 것이 필요해진다. 이 방식은 상태를 공유해야 하는 컴포넌트들이 많아지면 매우 복잡해진다. 그렇기에 state를 올리고 내리고 할 필요없도록 Redux를 사용하면서 각각의 컨테이너들에서 store에 바로 접근 가능하게 하면 코딩 및 디버깅이 훨씬 쉬워진다.
2. 리액트의 불변성을 유지하기 위함이다. state를 직접 변경(mutable)하게 될 경우 리액트가 state의 변화를 알아채지 못해 리렌더가 일어나지 않는다. 그러므로 상태를 직접 변형하지 않고, 항상 새로운 객체 및 배열을 만들어 setState를 호출하는 것이 좋다.

**Comment by taboowiths** [comment]
1. React의 state는 컴포넌트 내에서 생성이 가능하고, 컴포넌트 사이에 데이터를 주고받기 위해 props를 내려주는 방식으로 구현이 가능하다. 이 때 컴포넌트가 중첩될수록 props 또한 컴포넌트를 거쳐서 비효율적으로 전달되는 props drilling 현상이 일어나는데, Redux를 이용해 이러한 현상을 해결할 수 있다.
Redux는 store라는 전역 저장소를 사용하여 컴포넌트의 state를 공유하고, 또 각 컴포넌트에서 state에 쉽게 접근할 수 있도록 하여 state를 효율적으로 관리할 수 있다.

2. React에서 상태 변화를 감지할 때 state와 setState의 값을 비교하여 확인하게 되는데, state를 직접 변경하게 되면 React root의 render 함수가 상태 변화를 감지하지 못해 변경 사항이 반영되지 않는다. 따라서 setState()를 이용하여, render 함수가 변경 사항을 감지 및 반영할 수 있도록 한다.

**Comment by yeonsu-k** [comment]
1. 
> 프로젝트 규모가 커질수록 컴포넌트가 구조적으로 많이 생기고, 컴포넌트끼리 state 공유할 일이 많이 생깁니다. 이렇다면, 컴포넌트에 props를 전달하는 용도로만 쓰이는 경우도 생길 수 있는데, 이를 효과적으로 관리하기 위해서 Redux를 사용합니다. redux는 전역으로 상태를 관리하기 때문에 여러 컴포넌트를 거쳐 prop를 복잡하게 전달하지 않아도 손쉽게 값을 전달할 수 있습니다.

2. 
> 리액트의 불변성을 유지하기 위해서 입니다. 리액트의 state는 참조 타입으로 값을 직접적으로 변경할 경우, 변경사항을 인지하지 못하므로 컴포넌트가 재렌더링 되지않습니다. 하지만 setState를 사용하면 상태가 변경됨을 알고 재렌더링 됩니다.
