### ISSUE TITLE
[29회차] 부수효과, 라이프사이클

### ISSUE THREAD

**Issue by unhhyyeexx** [FrontCS-Study/CS-Study#14]
1. @unhhyyeexx 마운트란? 리액트에서 마운트와 렌더의 차이?
2. @taboowiths 리액트에서 다음과 같이 코드를 작성했을 때의 문제점은 무엇이며, 어떠한 방법으로 문제점을 해결할 수 있을까?
```jsx
const App = () => {
    const doSideEffect = () => {
    // do some side effect
    };
    
    doSideEffect();
    
    return <h1>Hello, World!</h1>;
}
```
3. @yeonsu-k 리액트에 있는 라이프사이클을 순서대로 간단히 설명해주세요.

**Comment by taboowiths** [comment]
1. 
마운트란 컴포넌트가 렌더링 되기 전 단계부터 렌더링이 되고 실제 DOM을 빌드하는 과정을 의미한다. 렌더링과의 차이점은, 맨 처음 컴포넌트가 렌더될 때 마운트의 과정을 겪으나 그 후 props나 state가 업데이트 될 때에는 마운트되지 않고 렌더링만 수행한다.

2. 
먼저 문제점은 1) `doSideEffect()`가 렌더링을 blocking 한다. 만약 함수의 실행 시간이 길면 해당 함수가 끝나기 전까지 컴포넌트가 렌더링되지 않는다. 2) 매 렌더링마다 함수가 실행되어 비효율적일 수 있다.

해결 방법은 `useEffect()` 훅을 사용한다. 따라서 렌더링이 모두 완료된 후에 해당 함수가 실행될 수 있도록 하고, 매 렌더링마다 실행되는 것이 아니라 특정 조건 하에 함수가 실행될 수 있도록 한다.

3. 
1) 마운트: 컴포넌트가 생성될 때 발생한다. 컴포넌트 안에서 인스턴트를 생성 및 초기화 하거나, 컴포넌트에서 작성된 JSX를 HTML으로 변환하는 함수 등을 실행한다.
2) 업데이트: 컴포넌트에서 props나 state의 변경이 일어났을 때, 혹은 부모 컴포넌트가 리렌더링 되었을 때 발생한다. 
3) 언마운트: 컴포넌트가 DOM에서 없어질 때 발생한다.

**Comment by yeonsu-k** [comment]
1.
> 리액트에서 mount는 라이프사이클 과정 중 하나로, 화면에 컴포넌트를 처음 생성할 때, 즉 DOM이 생성되고, 브라우저에 나타나나는 것을 의미합니다. render는 마운트나 업데이트 과정에서 컴포넌트가 최종적으로 리턴되어 웹 브라우저에 나타나는 것을 의미합니다. 처음 컴포넌트가 렌더될 때는 마운트가 실행되지만, props와 state가 변경되어 렌더 될 때는 마운트를 실행하지 않습니다.
2.
> Side Effect가 발생될 수 있습니다. `doSideEffect()`라는 코드는 매 렌더링마다 실행되어 예측하지 못한 결과를 맞이할 수 있기 때문에 UseEffect를 활용해서 조건부 렌더링이 될 수 있도록 만들어 side effect 문제를 해결할 수 있습니다.
3. 
> 리액트에서 라이프사이클은 크게 **생성(Mount) → 업데이트(Updating) →  제거(Unmount)** 로 나눌 수 있습니다. 
마운트는 컴포넌트가 생성 될 때, 발생하는 생명주기로, DOM이 생성되고, 웹 브라우저 상에 나타내는 것을 말한다.
업데이트는 props나 state가 바뀔 때, 부모 컴포넌트나 강제로 리렌더링 할 때 발생합니다.
마지막으로 언마운트는 컴포넌트가 화면에 사라질 때, 즉 DOM에서 제거하는 경우에 발생합니다.

**Comment by unhhyyeexx** [comment]
1. - 리액트 컴포넌트 생명 주기에서 마운트(Mount)는 DOM 객체가 생성되고 브라우저에 나타나는 것을 의미한다.
   - mount는 리액트가 처음으로 구성요소를 렌더링하고 실제로 초기 DOM을 빌드하는 것이다.
   - render는 DOM생성을 위해 함수가 호출될 때(혹은 클래스 컴포넌트에서 render 메소드가 호출될 때)를 말한다. 
   - 컴포넌트가 render될 때에는 mount과정을 거치지만, props나 state가 변경되어 render될 때에는 mount를 거치는 것은 아니다..
2. - 위 코드에서는 매 렌더링마다 side effect가 실행되어 예상치 못한 상황이 발생할 수 있고, side effect로 렌더링이 예상대로 혹은 정상적으로 수행되지 않을 수 있다.
   - `useEffect()` hook을 이용해 side effect를 수행한다.
3. 1. `Mount` 컴포넌트가 DOM에 추가되는 동작을 의미한다.
   2. `Update` 컴포넌트가 업데이트 되는 시점, 여러 번 실행될 수 있다.
   3. `Unmount` 컴포넌트가 DOM에서 제거되는 동작을 의미한다.
