### ISSUE TITLE
[30회차] hooks

### ISSUE THREAD

**Issue by taboowiths** [FrontCS-Study/CS-Study#15]
1. @taboowiths `useMemo`와 `useCallback`의 차이점은 무엇인가요?
2. @unhhyyeexx useLayoutEffect를 알고있나요? useEffect와의 차이는 무엇일까요?
4. @yeonsu-k React Hook을 사용해서 웹 성능 최적화를 해 본 경험이 있나요?

**Comment by taboowiths** [comment]
1. `useMemo`는 함수의 연산량이 많을 때, 이전의 결과값을 메모리에 저장하고 이를 재사용하기 위한 목적으로 사용한다. `useCallback`은 함수가 재생성되는 것을 방지하기 위한 목적으로 사용한다. props나 state, 혹은 부모 컴포넌트의 변화로 컴포넌트 내부 함수가 초기화되어 다시 실행되는 경우에 적용하여 최적화할 수 있다.

2. `useLayoutEffect`는 컴포넌트가 렌더된 후 실행되며, 렌더 후 effect, 그리고 페인트의 과정을 거친다. `useEffect`는 DOM의 레이아웃 배치와 페인트가 끝난 후 effect 함수를 호출하기 때문에, 내부 state값이 effect에 의해 변화되는 경우 깜빡임을 겪을 수 있다. `useLayoutEffect`는 DOM에 페인트 이전에 effect를 수행하여, 모든 값을 계산한 후 화면에 나오기 때문에 불필요한 깜빡임을 없앨 수 있다.

**Comment by unhhyyeexx** [comment]
1. 두 가지 hook모두 Memoization 기능을 제공하는 리액트의 hook으로, 불필요한 렌더링 또는 연산을 제어하는 용도로 성능 최적화에 그 목적이 있다. 
   useMemo는 Memoization된 '값'을 반환하는 함수이고, useCallback은 Memoization된 '함수'를 반환하는 함수이다. useMemo는 함수를 실행해서 그 실행값을 반환하지만, useCallback은 함수 자체를 반환한다.
   useMemo는 함수의 연산량이 많을 때 이전 결과값을 재사용하는 목적이고, useCallback은 함수가 재생성 되는 것을 방지하기 위한 목적으로 쓰인다.
2. useEffect는 컴포넌트가 render와 paint된 후 비동기적으로 실행된다. paint된 후에 동작하기 때문에, useEffect 내부에 DOM에 영향을 주는 코드가 있을 시 사용자 화면에 깜빡임이 있을 수 있다.
   useLayoutEffect는 컴포넌트가 render 된 후 동기적으로 실행된다. paint가 되기 전에 동작하기 때문에 DOM에 영향을 주는 코드가 내부에 있더라도 사용자는 깜빡임을 경험하지 않는다.
3. 없습니당...

**Comment by yeonsu-k** [comment]
1. useMemo와 useCallback의 차이점은 무엇인가요?
> useMemo는 연산된 값을 기억하여 값을 재사용하는 목적이고, useCallback은 함수를 기억해서 함수가 재생성 되는것을 방지하기 위한 목적으로 사용됩니다.

2. useLayoutEffect를 알고있나요? useEffect와의 차이는 무엇일까요?
> 가장 큰 차이점은 실행되는 시점입니다.  
useEffect는 화면에 컴포넌트가 그려진 후에 비동기적으로 호출되고, useLayoutEffect는 화면에 그려지기 전에 동기적으로 호출됩니다. 때문에 비동기 처리 값이 즉시 보여야한다던가, 애니메이션 구현에 화면 깜빡임 없이 보여주기 위해서는 useLayoutEffect를 사용해야합니다.

3. React Hook을 사용해서 웹 성능 최적화를 해 본 경험이 있나요?
> useMemo나 useLayoutEffect..?
