### ISSUE TITLE
[31회차] SPA, SSR, CSR, SEO

### ISSUE THREAD

**Issue by unhhyyeexx** [FrontCS-Study/CS-Study#16]
1. @unhhyyeexx CSR 과 SSR의 차이가 무엇인가요?
2. @taboowiths SPA 방식을 사용하게 된 배경이 무엇인가요? (MPA와 비교)
3. @yeonsu-k SEO는 무엇인가요? SEO을 하기위해 어떤 방법을 적용했는지 경험을 공유해주세요.

**Comment by taboowiths** [comment]
1. 
CSR과 SSR의 차이는 서버에서 응답 받은 HTML 파일의 상태에 있다. CSR은 브라우저가 서버에 요청을 보내면, 서버가 해당 요청에 따른 CSS와 JS의 링크만 있는 빈 HTML 파일을 응답하고, 브라우저에서는 받은 HTML에서 필요한 JS 파일을 다운 받은 후에 동적으로 HTML을 구성하여 페이지를 보여준다. 반면 SSR은 브라우저가 서버에 요청을 보내면, 화면에 띄울 준비가 되어 있는 HTML 파일을 만들어 브라우저에 보내 즉시 렌더링하게 된다. 이 때 JS는 적용되기 전이기 때문에 사용자 조작이 불가능하며, 필요한 JS 파일을 다운 받은 후에 연결이 완료되면 그 때 사용자 조작이 가능하게 된다.

2.
SPA를 사용하게 된 배경은, 기존에 사용하던 MPA의 한계에서 비롯되었다. MPA는 하나의 애플리케이션이 여러 개의 페이지로 구성되어 있어, 클라이언트가 새로운 페이지를 요청할 때마다 서버로부터 CSS 등을 포함한 정적 리소스를 다시 받아와야 하기 때문에 속도 저하 등의 문제가 발생하게 된다.
SPA 방식은 하나의 애플리케이션에 하나의 페이지로만 구성되며, 초기에 필요한 정적 리소스드를 한 번에 받고, 이후 새로운 페이지에 대한 요청이 있을 때마다 필요한 부분에 대한 데이터만 받아 갱신하여 리렌더링한다.

3. 
SEO는 검색엔진의 결과로 웹사이트의 상위 노출도를 올리는 작업을 말하는데, 즉 검색엔진이 쉽게 이해할 수 있는 형태로 웹사이트를 최적화하는 것을 말한다.

**Comment by unhhyyeexx** [comment]
1. CSR은 Client Side Rendering, SSR은 Server Side Rendering의 약자로, 말 그대로 어느 Side에서 렌더링을 준비하느냐에 따라 나뉘는 개념이다. 
   CSR은 브라우저가 JS 파일을 다운로드 하고 동적으로 DOM을 생성하는 시간을 기다려야 하기 때문에 초기 로딩속도가 느리지만, 이후 페이지 일부 변경 시에는 서버에서 해당 데이터만 요청하면 되기 때문에 이후 구동속도는 빠르다. 반면, SSR은 모든 데이터가 이미 HTML에 담긴 채 브라우저에 전달되어 SEO에 유리하고, JS코드를 다운받고 실행하기 전에 사용자가 이미 HTML이 렌더링 된 화면을 볼 수 있어 초기 구동속도가 빠르다.
2. MPA 방식을 사용할 때는 페이지 이동 시에 불필요한 템플릿이 중복되어 로딩되고, 새로운 페이지를 요청하면 리로딩이 발생하고 이에 깜빡거리는 현상이 발생한다. 또한 모바일 앱 개발 시에 추가적인 백엔드 작업이 필요해 개발이 복잡해진다. 이를 해결하기 위해 SPA 방식이 나왔다.
3. SEO란 Search Engine Optimization의 약자로, "검색엔진 최적화"라는 의미이다. 이는 웹 사이트의 가시성을 향상시키고 검색 엔진 결과 페이지에서 상위에 노출되도록 하는 노력이다.

**Comment by yeonsu-k** [comment]
1. 

   > CSR과 SSR의 렌더링을 하는 위치에 따라 구분됩니다.  
   > CSR은 최초에 한번 서버로부터 페이지를 로딩하여 보여주고 이후에는 사용자의 요청에 따라 일부만 렌더링을 하는 방식입니다.
   > SSR은 서버로부터 완성된 HTML파일을 받아 렌더링하는 방식으로 사용자가 요청을 하면 서버에서는 새로운 html,view와 렌더링하여 사용자에게 반환합니다.
   >
   > 이러한 방식 때문에 초기 구동 속도는 상대적으로 CSR이 SSR보다 느리지만 일부만 변경되기 때문에 화면 깜빡임이 없고, SSR은 초기 구동속도는 빠르지만 요청때마다 html을 새로 그리기 때문에 화면깜빡임이 있습니다.

2. 

   > MPA는 사용자가 요청 할 때마다 새로운 페이지에 데이터를 가져와 HTML형태로 변환 처리를 해야하는데 서비스 규모가 커짐에 따라 서버측 부담이 커지기 때문에, SPA를 도입하게 되었습니다. 
   > SPA는 최초 접근시 모든 리소스를 다운로드하고 이후 사용자 요청에 따라 응답만 하면 되기 때문에 서버 부하를 줄일 수 있습니다.
   > 이 밖에도 모바일 플랫폼이 활성화 되면서 웹 앱이 중요하게 되었고, MPA는 화면 깜박임처럼 사용자 경험을 좀 더 향상 시키기 위해 SPA를 도입하게 되었습니다. 

3. 

   > SEO는 광고가 아닌 자연 검색 엔진으로 검색결과에 상위 노출시키기 위한 방식을 의미합니다.
   > SEO를 사용해본 경험은 없지만 CSR인 경우에는 meta 태그를 사용할 수 있는 별도의 라이브러리를 설치하거나 리액트에는 Next.js를 vue에는 nuxt.js를 사용하여 SSR 렌더링 형식으로 구현하여 향상시킬 수 있는걸로 알고 있습니다.
