### ISSUE TITLE
[32회차] Next.js

### ISSUE THREAD

**Issue by unhhyyeexx** [FrontCS-Study/CS-Study#17]
1. @unhhyyeexx Next.js에서 SSG와 SSR의 차이는? 
2. @taboowiths next.js의 렌더링 과정을 설명해주세요. (pre-rendering, hydration)

**Comment by taboowiths** [comment]
1.
SSR와 SSG의 차이는 html 파일을 만드는 시점에 있다. SSR은 매 요청마다 해당하는 페이지에 대한 html을 렌더링하여 클라이언트에 전달한다. SSG는 모든 페이지에 대한 html을 빌드할 때 생성하고, 이후 요청이 들어올 때마다 만들어 둔 html를 재사용한다. 따라서 사용자의 요청에 빠르게 응답할 수 있으나, 사용자와의 상호작용이 있는 경우, 즉 매 요청마다 페이지의 내용이 변경되어야 하는 경우에는 적합하지 않다. 해당 경우에는 SSG보다 SSR이 더 적합하다.

2. 
1) 클라이언트에서 요청한 페이지의 컴포넌트를 pre-rendering 하여, 미리 서버에서 생성한 html을 전달하여 사용자에게 화면을 보여준다.
2) html을 전달한 직후, JS 코드를 클라이언트에 전달하여 DOM 요소에 이벤트 리스너를 적용하는 hydration 과정을 거친다.

**Comment by yeonsu-k** [comment]
1.
> 서버에서 HTML을 보내준다는 차원에서는 SSR과 유사하나, 요청할 때 즉시만드느냐 혹은 미리 만들어 놓느냐에 따라 차이가 있다.
> SSR은 요청 시 서버에서 즉시 HTML을 만들어 응답하기에 데이터가 달라지거나 자주 바뀌어서 미리 만들어 두기 어려운 페이지에 적합하다.  
> SSG는 페이지들을 서버에 미리 만들어 둔 후에 요청 시 해당 페이지를 응답하는 것이므로 바뀔 일이 거의 없어 캐싱해 두면 좋은 페이지에 사용된다.

2. 
> 1. 클라이언트에게 웹 페이지를 보내기 전에 Server Side 단에서 미리 웹 페이지를 **Pre-Rendering** 한다. 
> 2. 그 다음, 이 자바스크립트 코드들이 이전에 보내진 HTML DOM 요소 위에서 한번 더 렌더링을 하면서, 각자 자기 자리를 찾아가며 매칭이 된다. 이 과정을 **Hydrate**라고 부른다.

**Comment by unhhyyeexx** [comment]
1. Next.js에서는 사전 렌더링 방식으로 SSG와 SSR 두가지 방식을 제공하고 있으며, 두 가지 방식을 섞어서도 사용이 가능하다. 사전 렌더링에서 정적으로 페이지를 생성하면 SSG(정적 생성), 동적으로 페이지를 생성하면 SSR(서버 사이드 렌더링)이다.
   SSG는 build 타임에 HTML파일을 미리 생성해놓고 이를 요청이 있을 때마다 재사용 하는 방식이다. 빌드 시, 미리 생성된 HTML 파일을 CDN에 캐시해놓고, 유저의 요청이 있을 때마다 재사용을 할 수 있어 성능적으로 유리하다.
   SSR은 요청이 있을 때마다 필요한 HTML 파일을 생성하는 방식이다.
2. 뼈대만 있는 HTML이 아닌, 서버로부터 말 그대로 사전에 렌더링된 HTML 파일을 받아와 화면을 먼저 출력하고, JS 파일을 받아와 클라이언트에 전달해 DOM에 적용하는 과정(hydrate)을 거치게 된다.
