### ISSUE TITLE
[34회차] DOCTYPE

### ISSUE THREAD

**Issue by taboowiths** [FrontCS-Study/CS-Study#19]
1. @taboowiths DOCTYPE은 왜 선언해야 하나요?

**Comment by yeonsu-k** [comment]
1.
> 크로스 브라우징을 위해 사용합니다. 
> DOCTYPE를 선언하지 않을 경우, 각 브라우저의 렌더링 엔진에 따라 다르게 레이아웃을 보여줄 수 있습니다. 따라서 DOCTYPE을 선언하여 모든 브라우저들이 HTML을 동일하게 인식할 수 있도록 반드시 선언해야합니다.

**Comment by taboowiths** [comment]
1.
Doctype은 웹 문서가 어떤 버전을 기반으로 생성되었는지 표기하는 역할을 하고, 이를 기반으로 렌더링 모드를 설정하여 브라우저가 문서를 올바르게 표시할 수 있도록 한다.
Doctype을 선언한 경우 표준 모드로 작동하여 개발자가 의도된 대로 html과 css가 표시될 수 있으나, 선언하지 않은 경우 호환 모드로 작동하여 의도치 않은대로 표시될 수 있다.

**Comment by unhhyyeexx** [comment]
1.  doctype이란 document type의 약자로 웹 문서가 어떠한 형식으로 작성되었는지 문서 형식을 선언하는 것이다. 
doctype을 선언하지 않으면 쿼크 모드로 렌더링하여 같은 내용의 html문서라도 각 브라우저의 환경에 따라 전혀 다른 결과물로 출력될 수 있다. 그러므로 각 브라우저가 html 문서를 동일하게 인식할 수 있도록 하고, 문서 간 호환성을 높이기 위해 doctype을 선언한다.
