### ISSUE TITLE
[35회차] 웹 표준 및 웹 접근성

### ISSUE THREAD

**Issue by taboowiths** [FrontCS-Study/CS-Study#20]
1. @taboowiths 웹 표준과 웹 접근성에 대해 설명해주세요.
2. @yeonsu-k 크로스 브라우징에 대해 설명해보세요. 이를 고려하여 개발을 한 경험이 있나요?

**Comment by taboowiths** [comment]
1. 
웹 표준이란 운영체제나 브라우저에 관계 없이 동일한 결과를 보이게 하는 것을 의미한다. 이를 위해 표준 문법을 잘 준수하는 것 뿐만 아니라 시맨틱 태그를 사용한 구조적인 마크업, 레이아웃, Javascript 등을 이용한 동적 코드를 분리하여 사용하는 것 또한 포함된다.
웹 접근성이란 모든 사람(비장애인, 장애인, 어린이, 노인 등을 포함)이 어떠한 환경에서도 전문적인 지식 없이도 사이트에서 제공하는 모든 정보에 접근할 수 있는 것을 말한다. 

2.
크로스 브라우징이란 표준화된 웹 기술을 사용하여 어느 운영체제나 브라우저에 치우쳐 최적화되지 않고, 공통된 요소 등을 사용하여 동등한 결과가 나오도록 하는 것을 말한다. 이 때 운영체제나 브라우저에 따라 렌더링의 결과가 나오기 때문에, 완전히 동일한 결과보다는 차별되지 않도록 하는 것에 집중한다.

**Comment by unhhyyeexx** [comment]
1. 웹 표준은 웹에서 사용되는 기술들의 표준화를 의미한다. 사용자가 어떤 브라우저나 기기를 사용하더라도 홈페이지 화면을 동일하게 볼 수 있도록 하는 것이 웹 표준이다. 
   웹 접근성은 신체적, 환경적 조건에 관계없이 인터넷을 통해 정보에 접근하고 이용할 수 있도록 하는 것이다. 인터넷을 더욱 공평하고, 인종, 성별, 연령, 장애 유무 등과 상관 없이 모두가 이용할 수 있는 공간으로 만드는 것을 목표로 한다.

2. 크로스 브라우징은 웹 페이지가 다양한 웹 브라우저에서 동일한 방식으로 작동하는 기능이다. Chrome, IE, Safari, Firefox등의 여러 웹 브라우저에서 동일한 사용자 경험을 제공할 수 있어야 한다.
   크로스 브라우징을 고려하지 않고 웹 페이지를 작성하면, 레이아웃이 깨지거나, 구현한 기능이 제대로 작동하지 않는 등의 문제가 발생한다. 따라서 웹 표준을 준수하여 개발하고, 개발 단계에서 다양한 브라우저로 테스트 하는 작업도 필요하다.

**Comment by yeonsu-k** [comment]
1. 
> 웹 표준이란 웹에서 표준적으로 사용되는 기술이나 규칙을 의미합니다. 웹 접근성은 신체적,환경적 조건에 관계없이 웹에 접근하고 이용할 수 있도록 하는 것을 의미합니다. 웹 표준에 맞춰 제작할 때, 사용자가 어떤 브라우저나 기기에도 동일한 화면과 기능을 이용할 수 있기 때문에, 웹 표준에 웹 접근성이 포함되어있는 개념입니다.

2. 
> 크로스 브라우징은 간단히 말해 웹 호환성, 브라우저 간의 호환성을 보장하는 작업을 의마합니다. 다양한 브라우저와 기기의 렌더링 엔진이 소스 코드들을 동일하게 해석하지 못 할 수 있기 때문에, 웹 표준 기술을 적용해 모든 브라우저 기기와 사이트에 의도된대로 보여지게 해야합니다. 크로스브라우징을 해결하기위해서 DOCTYPE을 선언하고, 반응형 웹 페이지를 제작하는 경험이 있습니다.
