### ISSUE TITLE
[36회차] SVG

### ISSUE THREAD

**Issue by yeonsu-k** [FrontCS-Study/CS-Study#21]
1. @yeonsu-k 반응형으로 이미지를 구현하는 방법을 아는대로 말해주세요.
2. @yeonsu-k 이미지 최적화 방법을 아는대로 말해주세요.

**Comment by taboowiths** [comment]
1.
이미지의 크기를 px이 아닌 em/rem, vh/vw, %를 이용하여 정의한다.
`<picture>` 태그나 `<img>`의 `srcset` 속성을 사용하여 여러 버전의 이미지를 지정한 후, 사용하기에 적합한 버전을 선택한다.

2. 
CSS sprite : 자주 사용하는 이미지나 아이콘을 사용할 때마다 불러오는 것이 아니라, 하나의 이미지 안에 해당 요소를 통합하여 불러온 후 `position`을 이용하여 각각의 이미지를 불러오는 방식.

Intersection Observer를 이용한 Lazy Loading: Lazy Loading은 렌더링 시 이미지를 불러오는 것이 아니라, 중요하지 않은 이미지를 미리 불러오지 않고 필요할 때마다 불러오는 방식. Intersection Observer를 이용하면 observer가 감지될 때마다 이미지를 불러오는 방식으로 최적화할 수 있다.

**Comment by unhhyyeexx** [comment]
1. 1. img 태그의 srcset과 sizes 라는 속성을 이용한다. 
   2. picture 태그를 사용할 수도 있다.
2. 1. 너비값 조정
   2. 최적화된 이미지 포맷 사용
   3. 이미지 고정값 사용
   4. lazy loading 등

**Comment by yeonsu-k** [comment]
1.
> HTML에서는 크게 ① *`<img>` 태그에 srcset 속성과 sizes 속성을 이용하는 방법*과 ② *`<picture>` 태그에 media와 srcset 속성을 이용하여 구현하는 방법* 2가지가 있습니다.  
① 방법은 사용할 이미지에 필요한 너비를 브라우저에게 알려주고 그 너비에 해당하는 파일이나 사이즈를 구현하는 형식인데요. srcset이 제대로 동작하는 웹 브라우저가 한정적이라서 따로 미디어 태그를 이용하여 구현하거나 `<picture>` 태그 방법으로 구현합니다.  `<picture>` 태그는 css없이 조건에 맞는 반응형 디자인을 구현할 수 있는 태그입니다.

2. 
> 최적화된 이미지 포맷과 여러 사이즈 이미지를 가지고 제공하는 방법이 있습니다.
