### ISSUE TITLE
[37회차] display, flexbox, grid

### ISSUE THREAD

**Issue by yeonsu-k** [FrontCS-Study/CS-Study#22]
1. @yeonsu-k inline요소와 block요소의 차이점은 무엇인가요?
2. @taboowiths flex와 grid가 동작하는 방식은 어떻게 되나요? display: flex / display: grid 를 설정하면 자식 block이 어떻게 구성되나요?

**Comment by yeonsu-k** [comment]
1.
> inline은 줄바꿈 없이 content크기만큼 너비를 가로폭을 가지며, 상하 크기와 여백에 프로퍼티를 줄 수 없습니다. 반면에, block은 항상 새 줄에서 시작하며, 상위 블록에 너비만큼 차지 합니다.(width 100%와 같음!) 또한 상하 크기와 여백을 줄 수 있습니다. 추가적으로 inline-block속성을 사용하면 이 두 가지 특징을 모두 사용할 수 있습니다.
2.
> flex와 grid 요소의 크기가 불분명한 상태에서도 효율적으로 레이아웃을 정의할 수 있는 요소입니다. flex와 gird 모두 부모 컨테이너와 아이템들로 구성되어 있는데요. 부모 컨테이너에 display를 설정하면 각각의 item들이 flex의 경우 1차원 배열로, grid는 2차원 배열로 정렬할 수 있습니다.

**Comment by taboowiths** [comment]
1. 
block 요소는 1) 기본적으로 가로 영역을 전체 차지하며, 다음에 사용하는 요소는 줄바꿈이 된 것처럼 block 아래에 위치하게 된다. 2) width와 height, margin, padding 의 속성을 지정, 레이아웃에 반영된다.
inline 요소는 1) 가로 영역을 차지하지 않으며, 줄바꿈이 되지 않는다. 2) width와 height를 지정할 수 없다. margin과 padding 속성은 좌우 간격에만 반영되고, 상하 간격은 반영되지 않는다. 

2.
`display: flex` 설정 시 컨테이너 안의 아이템이 1차원의 가로로 배치된다. 이 때 아이템의 width는 자신이 가진 내용 만큼 차지하고, height는 컨테이너의 높이만큼 늘어난다. 
`display: grid` 설정 시 grid-template-row 혹은 grid-template-columns의 설정에 따라 2차원 그리드의 형태로 레이아웃을 설정할 수 있다.

**Comment by unhhyyeexx** [comment]
1. block값은 기본적으로 요소의 너비가 자신을 담고 있는 컨테이너의 100%가 되게 한다. 즉, 가로 한 줄을 다 차지한다. 또한 항상 줄 바꿈이 되어 새로운 라인에서 시작한다. 예시로, `<div>`, `<p>`, `<h>`, `<li>`, `<form>` 등이 해당한다.
   inline값은 콘텐츠를 딱 감쌀 정도의 크기 만을 갖게 된다. block과 달리 줄바꿈이 되지 않고, width, height 등을 이용해 크기를 변화시킬 수 없다. 대게 볼드, 이탤릭, 색상, 밑줄 등 글자나 문장에 효과를 주기 위해 사용한다. `<span>`, `<a>`, `<b>`, `<i>`, `<img>` 등이 해당한다.
2. Flex는 1차원으로 수평, 수직 영역 중 하나의 방향으로만 레이아웃을 나눌 수 있고, Grid는 2차원으로 수평, 수직을 동시에 영역을 나누는 것이 가능하다. Flex는 각 요소의 크기를 고려하지 않고, 컨테이너를 기준으로 요소의 배치를 결정하며, Grid는 요소의 크기와 위치를 모두 고려한다.
