### ISSUE TITLE
[18회차] 이벤트

### ISSUE THREAD

**Issue by yeonsu-k** [FrontCS-Study/CS-Study#4]
1. @yeonsu-k 이벤트 버블링과 이벤트 캡쳐링이란 무엇인가요?
2. @taboowiths 이벤트 위임이란 무엇이며, 이벤트 위임을 했을 때의 장점과 단점은 무엇인가요?
3. @unhhyyeexx 이벤트 전파에 대해 설명하고 이와 같은 현상이 일어나는 구조적인 이유에 대해 설명해주세요.

**Comment by yeonsu-k** [comment]
1. 이벤트가 발생하면 DOM 트리를 통해서 전파되는데, 이 과정에서 이벤트를 발생한 곳을 찾기 위해 해 상위에서 하위 방향으로 전파하는 방식을 "이벤트 캡쳐링", 반대로 이벤트가 발생 후 하위에서 상위로 전달되어 가는 방식을 "이벤트 버블링"이라고 합니다.
2. 상위 노드에서 하위 노드의 이벤트를 제어 하고 싶을 때 쓰는 방식으로 동적인 요소들에 대한 처리 수가 줄어 메모리를 절약할 수 있다는 장점이 있지만, 이벤트 위임을 사용하려면 이벤트가 반드시 버블링 되어야하는데 focus와 같은 몇몇 이벤트는 버블링이 되지 않는다는 단점이 있습니다.
3. 이벤트 전파는 DOM 트리 내 요소에 이벤트가 발생하면 DOM 트리를 통해 전파되는 것을 말합니다. HTML을 DOM Tree구조로 구성되어 있어 자식 요소만 클릭하더라도 부모 요소 영역 안에 위치하기 때문에 이벤트를 발생한 곳을 찾고, 이벤트 발생 후 빠져나오면서 전파가 발생할 수 밖에 없습니다.

**Comment by taboowiths** [comment]
1. 이벤트 버블링은 특정 엘리먼트에서 이벤트가 발생했을 때, 엘리먼트의 최상단에 있는 부모부터 이벤트가 전달되어 내려오는 것을 말하며, 이벤트 캡쳐링은 반대로 타겟 엘리먼트에서 최상단의 부모까지 이벤트가 전달되는 것을 말한다.

2. 이벤트 위임이란, 이벤트 전파의 특성을 이용하여 하위 요소에 각각 이벤트를 붙이지 않고, 상위 요소에서 하위 요소의 이벤트를 제어하는 것을 말한다. 
동적인 엘리먼트의 관리의 용이함, 이벤트 핸들러의 관리가 쉬워지는 등의 장점이 있으나, 버블링되지 않는 몇 이벤트에는 적용할 수 없다는 것과 예상치 못한 에러 상황이 발생할 수 있다는 단점이 존재한다.

3. 이벤트 전파란, 이벤트가 발생하였을 때, 이벤트 리스너를 실행시킬 대상 요소를 결정하는 과정을 의미한다. 즉 타겟 엘리먼트를 찾기 위해 이벤트 캡쳐링 -> 타겟 발견 및 이벤트 리스너 실행 -> 이벤트 버블링의 과정을 거친다.

**Comment by unhhyyeexx** [comment]
1. 
 - 이벤트 버블링이란 특정 화면 요소에서 이벤트가 발생했을 때 해당 이벤트가 더 상위의 화면 요소들로 전달 되어가는 특성이다. 가장 최상단 요소를 만날 때까지 이 과정이 반복되면서 요소 각각에 할당된 핸들러가 동작한다. `focus`이벤트와 같이 버블링 되지 않는 이벤트도 있지만, 몇몇 이벤트를 제외하곤 대부분의 이벤트는 버블링된다.
   - 이벤트 캡쳐는 이벤트 버블링과는 반대 방향으로 진행되는 이벤트 전파 방식이다. on<event>` 프로퍼티나 HTML 속성`, `addEventListener()`등을 이용해 할당된 핸들러는 캡처링에 대해 알 수 없기 때문에, 캡쳐링 단계에서 이벤트를 잡아내려면 `addEventListener`의 `capture`옵션을 true로 설정해야 한다.
2.
   - 이벤트 위임이란 하위 요소에 각각 이벤트를 붙이지 않고 상위 요소에서 하위 요소들의 이벤트를 제어하는 방식으로 이벤트 버블링을 이용한다.
   - 장점은 많은 핸들러를 할당하지 않아도 되기에 초기화가 단순해지고 메모리가 절약되며, 요소를 추가하거나 제거할 때 해당 요소에 할당된 핸들러를 수정하지 않아도 되기에 코드가 단순해진다.
   - 단점은 몇몇 버블링 되지 않는 이벤트는 사용할 수 없으며, 작은 수준이지만, 응답할 필요가 없는 이벤트에도 모든 상위 요소는 이벤트에 응답해야 하므로 cpu작업 부하가 늘어날 수 있다.
3. 
   - 이벤트 전파란 DOM 트리 내에 존재하는 요소에서 이벤트가 발생하면, DOM 트리를 통해 이벤트 객체가 전파되는 현상을 말한다.
   - 브라우저는 특정 화면 요소에서 이벤트가 발생했을 때 그 이벤트를 최상위에 있는 화면요소까지 전파시킨다. 즉, 브라우저가 이벤트를 감지하는 방식 때문에 이벤트 전파가 일어난다.
   - 또한 브라우저는 이벤트의 발생 의도를 파악할 수 없기 때문에 전부 수행해보는게,, 맞지 않을까 하는 제 의견입니당.,. 전파를 명시적으로 취소하려면 `stopPropagation()`, `preventDefault()`, `stopImmediatePropagation()`등을 사용하면 된다.
