### ISSUE TITLE
[20회차] 비동기프로그래밍

### ISSUE THREAD

**Issue by yeonsu-k** [FrontCS-Study/CS-Study#6]
1. @yeonsu-k 이벤트 루프 작동방식에 대해 말해주세요.
2. @taboowiths 다음 코드의 출력 내용과, 코드가 동작하는 순서를 설명하세요.
```javascript
setTimeout(function() { // (A)
    console.log('A');
}, 0);
Promise.resolve().then(function() { // (B)
    console.log('B');
}).then(function() { // (C)
    console.log('C');
});
``` 
3. @unhhyyeexx 자바스크립트에서 사용할 수 있는 비동기 프로그래밍 방법에 대해 설명해주세요.

**Comment by unhhyyeexx** [comment]
1. 일반적인 작업은 콜스택에서 이루어진다. 시간이 소요되는 작업들(`setTimeout`, 이벤트, HTTP 요청 메서드 등) 은 WebAPI에서 대기하다가 콜백큐로 보내진다. 이후 콜스택이 비워져있으면 콜백큐에 저장되어 있던 작업들이 콜스택으로 보내져 작업이 이루어진다.

2. 출력의 순서는 BCA순이다. 
   `setTimeout`함수는 콜백을 태스크큐에, Promise의 `then()`은 콜백을 마이크로태스크큐에 별도로 추가한다. 
   또한 큐의 우선순위는 마이크로태스크큐가 태스크큐보다 높기 때문에, 해당 코드에서는 콜백 A보다 B가 먼저 실행되고, B 실행 후에 `then()` 메서드에 의해 바로 콜백 C가 마이크로 태스크큐에 추가된다. 마이크로 태스크 큐가 또 생겼으므로 A보다 C가 먼저 실행되고 마이크로 태스크큐가 빈 후에 태스크큐에 대기하던 A가 실행된다.

3. 크게 3가지 방법으로 콜백함수, Promise, async/await 이 있다. 
   자바스크립트는 비동기 처리를 위한 하나의 패턴으로 콜백 함수를 사용한다. 하지만 콜백지옥에 빠질 수 있고, 한번에 여러 비동기 처리를 하는데 한계가 있다.
   Promise는 `then()`메서드를 통해 콜백을 등록하고, 작업이 끝났을 때 결과 값을 가지고 추가 작업을 하는 형식으로 비동기 처리가 가능하다.
   `async`/`await`은 더 편한환경에서 Promise를 다룰 수 있는 문법으로, 프로미스의 후속처리 메서드 없이 마치 동기처리처럼 Promise를 사용가능하다.

**Comment by taboowiths** [comment]
1. 이벤트 루프는 콜 스택과 태스트 큐를 계속 주시하면서, 매 순간 스택이 비어있는지 확인한다. 스택이 비어있다면 태스트 큐에 콜백이 들어올 때까지 대기 후, 첫 번째로 들어오는 콜백을 콜 스택으로 넘긴다. 

2. B -> C -> A 가 출력된다.
- setTimeout() 함수는 콜백 A를 태스트 큐에 넣고, Promise의 then() 메소드는 콜백 B를 마이크로태스크 큐에 넣는다.
- 코드 실행이 종료되면 이벤트 루프는 마이크로태스크 큐에 있는 콜백 B를 먼저 실행한다.
- 콜백 B를 실행하고 나면, 그 다음 then() 메소드가 콜백 C를 마이크로태스크 큐에 넣는다.
- then() 메소드가 종료되면 이벤트 루프가 마이크로태스크 큐에 있는 콜백 C를 실행시킨다.
- 마이크로태스크 큐가 빈 것을 확인하고, 그 다음으로 그 동안 대기하고 있던 콜백 A를 실행한다.

3. 콜백을 이용한 방식과 Promise 방식이 있다. 
- 콜백 방식은, 비동기 처리 방식이 종료된 후 실행되는 콜백을 통해 그 다음 실행하고자 하는 코드를 실행시킨다. 그러나 순차적으로 처리해야 할 코드가 많아질수록 비동기 함수를 연속적으로 사용해야 하는 불편함이 있다.
- Promise 함수는 비동기 처리 후 응답값에 따라 `then()` 혹은 `catch()` 를 통해 그 다음 작업으로 넘어갈 수 있도록 한다.

**Comment by yeonsu-k** [comment]
1. 이벤트 루프는 자바스크립트에서 비동기 함수를 처리할 수 있도록 도와주는 루프입니다. 
자바스크립트 엔진 내에 콜스택에과 브라우저의 태스크 큐를 반복적으로 상태를 체크하다가 콜스택이 비어있게 되면, 태스크 큐 내에 있는 가장 오래된(첫 번째 태스크)를 콜 스택으로 이동 시켜 실행 될 수 있게 합니다.  이때, 태스크 큐는 마이크로태스크 큐와 매크로태스크 큐로 나뉘게 되는데, 이벤트 루프는 마이크로태스크 큐의 모든 태스크들을 처리한 다음, 매크로태스크 큐의 태스크들을 처리합니다.

2. B C A 순으로 출력됩니다. 
비동기 함수나 콜백 함수들은 태스크 큐에 순차적으로 쌓아두고 이벤트 루프를 통해 함수를 하나씩 처리하게 되는데, 태스크 큐는 `promise` 함수를 담는 마이크로태스크 큐와 `setTime` 같은 함수를 담는 매크로 태스크 큐로 구분합니다. 이벤트 루프는 마이크로 태스크 큐를 우선적으로 실행하기 때문에 프로미스 함수인 B함수를 시작으로 C, A순으로 동작 하게 됩니다.

3. ~잘 모르겠다.~
크게 3가지로 콜백 함수,  Promise, async/await가 있습니다.
콜백 함수는 비동기 함수 내부에서 다음 작업을 호출하기 때문에 처리 순서를 정할 수 있지만, 순차적으로 처리할 함수가 많을 경우 함수 안에 함수가 반복되어 '콜백지옥'이라는 현상을 발생할 수 있습니다.
Promise는 비동기 함수의 성공과 실패 여부를 `then`과 `catch`라는 별도의 블록으로 구분해서 받을 수 있습니다. `resolve`와 `reject` 2개의 인자를 받아서, 비동기 처리가 성공하면 `then`형식의 `resolve`를 호출하고 실패하면 `catch`형식의 `reject`가 호출됩니다. 
async & await는 비동기 함수 호출이 모두 완료된 후 태스크를 실행할 수 있는. 즉, 비동기를 동기처럼 보이게 할 수 있는 키워드 입니다. async/await를 사용하면 await가 대기를 처리해주기 때문에, promise에서 사용하던 `.then`과 .`cath` 없이 이후 태스크를 처리할 수 있습니다.
