### ISSUE TITLE
[22회차] REST API

### ISSUE THREAD

**Issue by unhhyyeexx** [FrontCS-Study/CS-Study#8]
1. @unhhyyeexx REST가 무엇이며 RESTful 하다는 것은 무엇을 의미하는지 간단히 설명해주세요.
2. @yeonsu-k  Restful API의 메서드 종류를 말해보세요. 추가적으로 GET과 POST의 차이를 설명해주세요,
3. @taboowiths  HTTP 응답 상태 코드 중, '401'과 '403'의 차이는 무엇인가요?

**Comment by unhhyyeexx** [comment]
1. REST는  REpresentational State Transfer의 약자로, 자원을 정의하고 자원에 대한 주소를 지정하는 네트워크 아키텍처의 모음으로 자원(Resource)의 표현(Representation)에 의한 상태 전달을 뜻한다. 즉, 자원을 이름으로 구분하여 해당 자원의 상태를 주고받는 모든 것을 의미하는 것이다.
   REST API를 제공하는 웹 서비스를 RESTful하다고 할 수 있으며, RESTful 의 목적은 이해하기 쉽고 사용하기 쉬운 REST API를 만드는 것, 일관적인 컨벤션을 통해 API의 이해도 및 호환성을 높이는 것이다.

2. GET(리소스 취득), POST(리소스 생성), PUT(리소스 전체 교체), PATCH(리소스 일부 수정), DELETE(리소스 삭제)
3. 401은 Unauthorized 에러. 즉, 인증되지 않은 클라이언트거나, 인증정보가 유효하지 않아 요청이 거부된 상태이다. 403은 Forbidden에러로, 서버가 요청을 이해했지만, 권한이 없어 요청이 거부된 상태이다.
   로그인을 하지 않고 어떤 정보를 요청하는 경우 401을, 로그인을 했지만 해당 유저가 접근할 수 없는 정보를 요청하는 경우 403을 반환한다.
   여기서 403을 반환한다는 것은 해당 리소스가 존재한다는 것을 내포할 수 있으므로, 자원 존재 여부를 드러내고 싶지 않다면 403 대신 404 등 다른 상태코드를 반환하는 것이 좋을 수도 있다.

**Comment by taboowiths** [comment]
1. REST란 자원의 이름을 이용해 자원의 내용을 주고 받는 모든 행위를 말하며, 구체적으로 HTTP URI를 이용해서 자원을 명시하고, HTTP 메소드를 통해 자원의 CRUD 행위를 수행하는 것을 말한다. RESTful하다는 것은 REST의 원칙을 준수하는 시스템이라고 할 수 있으며, REST의 특성을 반영한 API를 사용하는 웹 서비스를 RESTful 하다고 할 수 있다.
2. GET, POST, PUT, DELETE / 각각 자원 조회, 새로운 자원 추가, 기존 자원 수정, 기존 자원 삭제의 기능을 한다.
3. 401은 인증되지 않은 클라이언트가 보호된 자원을 요청할 때 응답하는 코드이며, 403은 클라이언트의 인증 여부와 관계 없이 서버 측에서 응답하고 싶지 않은 자원을 요청받았을 때 사용한다.

**Comment by yeonsu-k** [comment]
1. REST는 HTTP를 기반으로 클라이언트가 서버의 리소스에 접근하는 방식을 규정한 것을 의미합니다.
Restful하다는 것은 REST API 의 설계 원칙에 지키며 API를 설계한 것을 의미하며, URI는 리소스를 이해할 수 있도록 명사로 작성하고, 동작은 HTTP 메서드(POST, GET, PUT, DELETE 등)를 이용하여 표현합니다.

2. GET, POST, PUT, DELETE 4가지가 있습니다.
   GET은 데이터를 조회할 때, POST는 데이터를 생성할 때 주로 사용합니다. 또한 GET은 URL에 파라미터로 데이터를 요청해서 body가 없는 반면에, POST는 body에 데이터를 담아 보냅니다. 

3. 401은 비인증된 요청임을 의미하며, 403은 콘텐츠에 접근할 권한을 가지고 있지 않았을 때 에러 코드 입니다.   
(추가) 401은 클라이언트가 인증되지 않아서 요청을 처리할 수 없음을 알리는 에러 코드이다. 예를 들어서 로그인이 되지 않은 상태에서 무언가 요청하는 경우에 볼 수 있다. ( 서버에 데이터를 요청하고 사용하는데 앞서 입구컷 같은...? )
403은 요청은 이해했지만, 클라이언트가 해당 요청에 대한 권한이 없다는 에러 코드이다. 예를 들어 로그인된 사용자가, 다른 사용자의 데이터를 요구하는 경우 볼 수 있다. ( 리소스 요청에 문제는 없지만 사용자 접근 권한이 없을 때 발생하는 것 같다...! )
