### ISSUE TITLE
[23회차] Promise

### ISSUE THREAD

**Issue by unhhyyeexx** [FrontCS-Study/CS-Study#9]
1. @unhhyyeexx Promise와 Callback 함수 방식과의 차이점을 설명해주세요.
2. @taboowiths Promise의 핸들러인 `.then`, `.catch`, `.finally`에 대해 설명해주세요.

**Comment by unhhyyeexx** [comment]
1. 콜백 함수는 함수 안에서만 결과값 처리를 할 수 있고 결과값을 알 수 있어 콜백 밖에서는 비동기에서 온 값을 알 수 없다. 하지만 Promise를 사용하면 비동기 로직에서 처리된 결과값이 promise 객체에 저장되기 때문에 로직 밖에서도 사용이 가능해 코드 작성이 용이해진다.
2. 프로미스 핸들러는 프로미스의 상태에 따라 실행되는 콜백함수를 말한다. 
   1. `.then()` : 프로미스가 이행됐을 때 실행할 콜백함수 등록, 새로운 프로미스 반환
   2. `. catch()` : 프로미스가 거부됐을 때 실핼할 콜백함수 등록, 새로운 프로미스 반환
   3. `.finally()` : 프로미스의 이행, 거부에 상관없이 실행할 콜백함수 등록, 새로운 프로미스 반환

**Comment by yeonsu-k** [comment]
1. Promise와 Callback함수는 비동기 작업을 순차적으로 처리하기 위해 사용하는 함수입니다. callback함수는 함수 안에서만 결과값을 알 수 있기 때문에, 처리 역시 함수 내부에서 해야합니다. 콜백함수와 달리 promise는 비동기로 처리된 결과 값이 promise객체에 저장되기 때문에 로직 밖에서도 사용 가능합니다. 
2.
  `.then()` : 프로미스가 이행(fulfilled)되었을 때 실행할 콜백 함수를 등록하고, 새로운 프로미스를 반환
  `.catch()` : 프로미스가 거부(rejected)되었을 때 실행할 콜백 함수를 등록하고, 새로운 프로미스를 반환
  `.finally()` : 프로미스가 이행되거나 거부될 때 상관없이 실행할 콜백 함수를 등록하고, 새로운 프로미스를 반환

**Comment by taboowiths** [comment]
1. Callback 방식과 Promise 방식은 함수가 비동기적으로 실행되고 반환되는 결과에 따라 다음 코드를 처리하는 방식이지만, Callback 방식은 그 결과값을 Callback 함수 외부에서 접근할 수 없어 항상 함수 내부에서 처리해야 한다. 따라서 연속적인 비동기 처리 시 Callback 함수가 계단식으로 쌓여 가독성 및 에러 처리가 어려워진다. 
반면 Promise 방식은 비동기의 결과값이 Promise 객체에 저장되기 때문에 함수 외부에서 처리할 수 있게 되고, 이러한 결과값을 가지고 .then(), .catch() 등 핸들러에 의해 순차적으로 처리할 수 있으므로 가독성 및 에러 처리가 수월해질 수 있다.

2. .then() : Promise 객체의 state가 `pending`에서 `fulfilled` 상태가 되었을 경우 내부 콜백 함수가 실행되며 새로운 Promise 객체를 반환한다.
.catch() : Promise 객체의 state가 `reject` 상태가 되었을 경우 실행된다. 
.finally() : `pending` 이후,  Promise 객체의 state 결과값에 상관 없이 실행되며 새로운 Promise 객체를 반환한다.
